import type { RuntimeStep } from '../types';

export const GITGUARDIAN_SECRET_SCRIPT: RuntimeStep[] = [
  {
    channel: 'sdk',
    phase: 'identified',
    delayMs: 250,
    label: 'Webhook received from GitGuardian',
    detail: 'POST /webhooks/gitguardian · 412 byte payload · signature verified',
    plainEnglish: 'GitGuardian just told the agent: "we found a leaked secret."',
    sdkEvent: { type: 'agent.create', payload: 'model: composer-2 · 7 MCPs configured' },
  },
  {
    channel: 'sdk',
    phase: 'identified',
    delayMs: 200,
    label: 'agent.send() — agent-bc-29f4d1a8',
    detail: 'prompt: 612 chars · cloud.repos: acme/payments-service@main',
    plainEnglish: 'The Cursor agent boots up with the right tools and the right prompt for this incident.',
    sdkEvent: { type: 'agent.send', payload: 'agentId=bc-29f4d1a8 · status=PENDING' },
  },
  {
    channel: 'sdk',
    phase: 'identified',
    delayMs: 350,
    label: 'status.change → RUNNING',
    detail: 'workspace provisioned · branch base captured',
    plainEnglish: 'Agent is live and starting work.',
    sdkEvent: { type: 'status.change', payload: 'PENDING → RUNNING' },
  },

  {
    channel: 'gitguardian',
    phase: 'context',
    delayMs: 500,
    label: 'Fetching incident detail',
    detail: 'GET /incidents/41822 · 3 secrets exposed in payments-service',
    plainEnglish: 'Asks GitGuardian: "what exactly was leaked?" \u2014 3 secrets in payments-service.',
    sdkEvent: { type: 'tool.call', payload: 'gitguardian-mcp · incidents.get(41822)' },
  },
  {
    channel: 'gitguardian',
    phase: 'context',
    delayMs: 400,
    label: 'Owner resolved via Asset Graph',
    detail: 'team: payments-eng · service: payments-service · sha: f4e9a1c2',
    plainEnglish: 'Figures out which team owns the affected service so the right humans get the alert.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 397ms · 3 matches' },
  },

  {
    channel: 'opus',
    phase: 'context',
    delayMs: 800,
    label: 'Claude Opus: forming response plan',
    detail: 'Containment first · 3 secrets need rotation in parallel · cleanup PR after',
    plainEnglish: 'Pauses to think. Decides: stop the bleeding first, fix the code second, document third.',
    sdkEvent: { type: 'assistant', payload: '"Plan: rotate AWS, roll Stripe, publish to Vault, then code cleanup."' },
  },

  {
    channel: 'aws',
    phase: 'containment',
    delayMs: 600,
    label: 'iam.create_access_key()',
    detail: 'user: payments-service-deploy · new key AKIAXXXXXXXXX1F4',
    plainEnglish: 'Asks AWS to make a brand-new access key for the affected service.',
    sdkEvent: { type: 'tool.call', payload: 'aws-mcp · iam.create_access_key(user=payments-service-deploy)' },
  },
  {
    channel: 'aws',
    phase: 'containment',
    delayMs: 350,
    label: 'iam.update_access_key(status=Inactive)',
    detail: 'leaked key AKIAIOSFODNN7EXAMPLE marked Inactive',
    plainEnglish: 'Turns off the leaked key. Even if attackers grabbed it, it\u2019s now useless.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 314ms' },
  },
  {
    channel: 'aws',
    phase: 'containment',
    delayMs: 450,
    label: 'organizations.attach_policy()',
    detail: 'explicit deny SCP attached at org root for leaked AccessKeyId',
    plainEnglish: 'Adds a belt-and-suspenders rule across the whole AWS org: nothing the leaked key tries can succeed.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 449ms' },
  },

  {
    channel: 'stripe',
    phase: 'containment',
    delayMs: 500,
    label: 'POST /v1/api_keys/{id}/roll',
    detail: 'replacement rk_live_*** captured',
    plainEnglish: 'Asks Stripe for a new payment-processing key. The old one is now invalid.',
    sdkEvent: { type: 'tool.call', payload: 'stripe-mcp · keys.roll(rk_live_…EXAMPLE)' },
  },
  {
    channel: 'stripe',
    phase: 'containment',
    delayMs: 250,
    label: 'Stripe restricted key rolled',
    detail: 'old key revocation propagated · 0s replication lag',
    plainEnglish: 'Stripe confirms: the old key is revoked everywhere.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 248ms' },
  },

  {
    channel: 'vault',
    phase: 'containment',
    delayMs: 500,
    label: 'kv.write(payments-service/aws-access-key-id)',
    detail: 'version: 23 · path: secret/data/payments-service/aws-access-key-id',
    plainEnglish: 'Saves the new AWS key in HashiCorp Vault so the running app can pick it up automatically.',
    sdkEvent: { type: 'tool.call', payload: 'vault-mcp · kv.write(...)' },
  },
  {
    channel: 'vault',
    phase: 'containment',
    delayMs: 280,
    label: 'kv.write(payments-service/stripe-restricted-key)',
    detail: 'version: 14',
    plainEnglish: 'Saves the new Stripe key in Vault too. The app keeps running, no downtime.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 278ms' },
  },

  {
    channel: 'composer',
    phase: 'remediation',
    delayMs: 700,
    label: 'Composer: editing payments.ts',
    detail: 'replacing literals with getSecret() references',
    plainEnglish: 'Edits the source code: removes the hardcoded password, replaces it with a safe lookup from Vault.',
    sdkEvent: { type: 'assistant', payload: 'edit payments.ts · 6 lines' },
  },
  {
    channel: 'composer',
    phase: 'remediation',
    delayMs: 500,
    label: 'Adding .gitleaks.toml allowlist',
    detail: 'whitelisting AWS-published example credential pattern',
    plainEnglish: 'Adds a tiny config file so the scanner doesn\u2019t flag the same false positives over and over.',
    sdkEvent: { type: 'tool.call', payload: 'github-mcp · contents.create(.gitleaks.toml)' },
  },
  {
    channel: 'codex',
    phase: 'remediation',
    delayMs: 600,
    label: 'Codex review · ✓ no behavioral change',
    detail: 'types preserved · callers unaffected · style ✓',
    plainEnglish: 'A second AI reviews the code change like a senior engineer would. Confirms it\u2019s safe.',
    sdkEvent: { type: 'assistant', payload: '"Patch reviewed. Safe to ship."' },
  },

  {
    channel: 'shell',
    phase: 'remediation',
    delayMs: 450,
    label: 'npx tsc --noEmit',
    detail: '✓ no type errors',
    plainEnglish: 'Runs the type-checker. Code compiles cleanly.',
    sdkEvent: { type: 'tool.call', payload: 'shell · tsc --noEmit' },
  },
  {
    channel: 'shell',
    phase: 'remediation',
    delayMs: 400,
    label: 'npm run lint',
    detail: '✓ 0 errors · 0 warnings',
    plainEnglish: 'Runs the style checker. All good.',
    sdkEvent: { type: 'tool.result', payload: 'exit 0 · 397ms' },
  },
  {
    channel: 'shell',
    phase: 'remediation',
    delayMs: 500,
    label: 'gitleaks detect --no-banner',
    detail: '✓ 0 leaks · allowlist applied · 18 files scanned',
    plainEnglish: 'Runs the leaked-secret scanner one more time. Repo is now clean.',
    sdkEvent: { type: 'tool.result', payload: 'exit 0 · 488ms' },
  },

  {
    channel: 'github',
    phase: 'remediation',
    delayMs: 400,
    label: 'branch.create(cleanup/secret-purge-payments-service)',
    detail: 'base: main · author: cursor-agent',
    plainEnglish: 'Creates a new branch in GitHub for the proposed code changes.',
    sdkEvent: { type: 'tool.call', payload: 'github-mcp · git.refs.create(...)' },
  },
  {
    channel: 'github',
    phase: 'remediation',
    delayMs: 450,
    label: 'pulls.create #3142',
    detail: '"chore(security): remove leaked credentials, source from Vault"',
    plainEnglish: 'Opens a Pull Request asking a human to review and merge the fix. Agent never merges itself.',
    sdkEvent: { type: 'tool.result', payload: '201 Created · #3142' },
  },
  {
    channel: 'github',
    phase: 'remediation',
    delayMs: 500,
    label: 'pulls.create #3143 (DRAFT)',
    detail: '"chore(security): purge leaked credentials from history (REQUIRES TEAM APPROVAL)"',
    plainEnglish: 'Opens a second Pull Request \u2014 marked DRAFT \u2014 to scrub the secret from old commits. Dangerous, so humans must approve.',
    sdkEvent: { type: 'tool.result', payload: '201 Created · #3143 · draft: true' },
  },

  {
    channel: 'jira',
    phase: 'audit',
    delayMs: 500,
    label: 'Creating CUR-SEC-2118',
    detail: 'P0 · Security incident · components: payments-service, IAM, Stripe, Vault',
    plainEnglish: 'Files a Jira ticket with the full incident summary so the security team can track it.',
    sdkEvent: { type: 'tool.call', payload: 'jira-mcp · issues.create(...)' },
  },
  {
    channel: 'jira',
    phase: 'audit',
    delayMs: 320,
    label: 'CUR-SEC-2118 → Awaiting Review',
    detail: 'linked: GG #41822 · PR #3142 · PR #3143 · Vault v23',
    plainEnglish: 'Links every artifact \u2014 the GG incident, both PRs, the Vault version \u2014 to one ticket.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · status transitioned' },
  },

  {
    channel: 'slack',
    phase: 'audit',
    delayMs: 480,
    label: 'chat.postMessage(#security-incidents)',
    detail: 'structured incident summary · @on-call paged',
    plainEnglish: 'Posts in #security-incidents and pages the on-call human with a clean summary.',
    sdkEvent: { type: 'tool.call', payload: 'slack-mcp · chat.postMessage(...)' },
  },
  {
    channel: 'splunk',
    phase: 'audit',
    delayMs: 320,
    label: 'hec.event(secret_leak.contained)',
    detail: 'index: security_audit · sourcetype: cursor:agent:run',
    plainEnglish: 'Writes a structured record into Splunk so auditors can later prove this was contained quickly.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 318ms' },
  },

  {
    channel: 'gitguardian',
    phase: 'resolved',
    delayMs: 350,
    label: 'incidents.update(status=resolved)',
    detail: 'incident 41822 closed · resolution attached',
    plainEnglish: 'Tells GitGuardian: "this one is handled." The incident closes in their dashboard.',
    sdkEvent: { type: 'tool.result', payload: '200 OK · 348ms' },
  },

  {
    channel: 'sdk',
    phase: 'resolved',
    delayMs: 350,
    label: 'step.complete · all 27 steps emitted',
    detail: 'cumulative billed time: 58.0s · wall time: 22.4s',
    plainEnglish: 'Run finished. Total wall time: 22 seconds. Total agent work time: 58 seconds.',
    sdkEvent: { type: 'step.complete', payload: 'final step · agent ready to wait()' },
  },
  {
    channel: 'done',
    phase: 'resolved',
    delayMs: 280,
    label: 'agent.wait() → { status: "FINISHED" }',
    detail: 'artifacts ready for review',
    plainEnglish: 'Agent reports back FINISHED. Hands the work to a human reviewer.',
    sdkEvent: { type: 'agent.wait', payload: 'status: FINISHED · 5 artifacts' },
  },
];
