'use client';

import type { ResolvedScript } from '@/lib/sdk-demo/scripts/pick-script';
import type { RuntimeStep } from '@/lib/sdk-demo/types';
import { Shield } from 'lucide-react';

interface AuditTimelineProps {
  script: ResolvedScript;
}

const CHANNEL_LABEL: Record<string, string> = {
  sdk: 'cursor-sdk',
  gitguardian: 'gitguardian-mcp',
  wiz: 'wiz-mcp',
  snyk: 'snyk-mcp',
  okta: 'okta-mcp',
  crowdstrike: 'crowdstrike-mcp',
  splunk: 'splunk-mcp',
  zscaler: 'zscaler-mcp',
  aws: 'aws-mcp',
  stripe: 'stripe-mcp',
  vault: 'vault-mcp',
  github: 'github-mcp',
  jira: 'jira-mcp',
  slack: 'slack-mcp',
  opus: 'opus · triage',
  composer: 'composer · edit',
  codex: 'codex · review',
  shell: 'shell',
  codegen: 'codegen',
  done: 'complete',
};

function formatClock(ms: number): string {
  const total = Math.floor(ms / 1000);
  const millis = Math.floor(ms) % 1000;
  const hh = 14;
  const mm = 18 + Math.floor(total / 60);
  const ss = total % 60;
  return `${String(hh).padStart(2, '0')}:${String(mm).padStart(2, '0')}:${String(ss).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
}

export function AuditTimeline({ script }: AuditTimelineProps) {
  let cumulative = 0;
  const rows: Array<{ ms: number; step: RuntimeStep }> = [];
  for (const step of script.steps) {
    cumulative += step.delayMs;
    rows.push({ ms: cumulative, step });
  }
  const total = (cumulative / 1000).toFixed(1);

  return (
    <div className="w-full h-full bg-white text-[#111] overflow-y-auto">
      <div className="max-w-[820px] mx-auto px-8 py-8">
        <div className="flex items-center gap-3 mb-1">
          <div className="w-9 h-9 rounded-lg bg-[#0F62FE]/10 border border-[#0F62FE]/30 flex items-center justify-center">
            <Shield className="w-4 h-4 text-[#0F62FE]" />
          </div>
          <div>
            <p className="text-[10px] font-mono uppercase tracking-[0.18em] text-[#666]">
              Audit timeline · {script.meta.jiraId}
            </p>
            <p className="text-[20px] font-semibold leading-tight">{script.title}</p>
          </div>
        </div>
        <p className="text-[12px] text-[#666] mb-5">
          Generated by Cursor agent <span className="font-mono">{script.meta.agentId}</span> · MTTR {total}s · Cryptographically attested · SOC 2 CC7.1 evidence-grade
        </p>

        <div className="grid grid-cols-2 gap-3 mb-6">
          <Field label="Incident" value={script.meta.jiraSummary} />
          <Field label="Status" value="Resolved · Awaiting human review of PRs" />
          <Field label="Root cause" value={script.meta.rootCause} />
          <Field label="Remediation" value={script.meta.remediation} />
        </div>

        <div className="border-t border-[#e5e5e5] pt-4 mb-2">
          <p className="text-[11px] font-mono uppercase tracking-wider text-[#666] mb-3">
            Chronological actions ({rows.length})
          </p>
          <ol className="space-y-1.5">
            {rows.map(({ ms, step }, i) => (
              <li key={i} className="flex items-start gap-3 text-[12px]">
                <span className="font-mono text-[#666] shrink-0 w-[110px]">{formatClock(ms)}</span>
                <span className="font-mono text-[11px] uppercase tracking-wider text-[#0F62FE] shrink-0 w-[140px] truncate">
                  {CHANNEL_LABEL[step.channel] ?? step.channel}
                </span>
                <div className="flex-1 min-w-0">
                  <p className="text-[#111] leading-snug">{step.label}</p>
                  {step.detail && (
                    <p className="text-[11px] text-[#666] leading-snug mt-0.5">{step.detail}</p>
                  )}
                </div>
                <span className="text-[10px] font-mono text-[#999] shrink-0">cursor-agent</span>
              </li>
            ))}
          </ol>
        </div>

        <div className="border-t border-[#e5e5e5] pt-4 mt-6">
          <p className="text-[11px] font-mono uppercase tracking-wider text-[#666] mb-2">
            Linked evidence
          </p>
          <ul className="text-[12px] space-y-1">
            {script.meta.evidenceLinks.map((link, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="text-[#0F62FE]">▸</span>
                <span className="text-[#111]">
                  <span className="font-medium">{link.label}:</span>{' '}
                  <span className="font-mono text-[#666]">{link.ref}</span>
                </span>
              </li>
            ))}
          </ul>
        </div>

        <p className="text-[10px] text-[#999] mt-6 italic">
          This document was generated automatically by a Cursor Background Agent in response to a
          security event. Every action was performed by the agent with named MCP servers; no human
          credentials or sessions were used. Reviewer action: validate root cause, approve linked
          PRs.
        </p>
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-[10px] font-mono uppercase tracking-wider text-[#666] mb-0.5">{label}</p>
      <p className="text-[12px] text-[#111] leading-snug">{value}</p>
    </div>
  );
}
