'use client';

import { CHARACTERS } from '../data/characters';

export function TriageReportArtifact() {
  const reviewers = [CHARACTERS.park, CHARACTERS.chen, CHARACTERS.davis, CHARACTERS.kim];
  return (
    <article className="bg-white p-6 text-[#111827]">
      <header className="mb-4 border-b pb-3" style={{ borderColor: '#E5E7EB' }}>
        <div className="text-[10px] font-semibold uppercase tracking-widest text-[#6B7280]">
          Modernization triage · OrdersService
        </div>
        <h2 className="mt-1 text-2xl font-bold">Target-state plan · v1.2</h2>
        <p className="mt-1 text-[13px] text-[#6B7280]">
          Generated by Cursor after 3 calendar days of discovery. Reviewed and amended over 22 days with 4 named gates.
        </p>
      </header>

      <section className="mb-5">
        <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-[#6B7280]">Source state</h3>
        <div className="grid grid-cols-3 gap-3 text-sm">
          <Fact label="Runtime"      value="WebSphere 8.5 + EJB" />
          <Fact label="Database"     value="Oracle 12c (EE, EoL 2027)" />
          <Fact label="LOC"          value="180,000" />
          <Fact label="p99 latency"  value="1,240 ms" />
          <Fact label="Run-rate"     value="$70,000/mo allocated" />
          <Fact label="Maintainer"   value="None since 2019" />
        </div>
      </section>

      <section className="mb-5">
        <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-[#6B7280]">Target state</h3>
        <div className="grid grid-cols-3 gap-3 text-sm">
          <Fact label="Runtime"      value="AWS Lambda (Node 20)" />
          <Fact label="Database"     value="Aurora Serverless v2 (Postgres 15)" />
          <Fact label="API"          value="API Gateway (private)" />
          <Fact label="p99 latency"  value="340 ms" accent="#16A34A" />
          <Fact label="Run-rate"     value="$527/mo" accent="#16A34A" />
          <Fact label="IAM"          value="CIS §3.1, §4.2 compliant" />
        </div>
      </section>

      <section className="mb-5">
        <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-[#6B7280]">Override log</h3>
        <ul className="space-y-2 text-[13px]">
          <li className="rounded border-l-2 px-3 py-2" style={{ background: '#FEF3C7', borderColor: '#F59E0B' }}>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-[#78350F]">Day 3 · J. Park (Principal Architect)</div>
            <p className="mt-1">
              Extend dual-write from 7 to <strong>14 days</strong>. Add parity-diff Lambda (15-min cadence, fail-closed @ 0.01% drift).
              <span className="text-[#6B7280]"> Grounded: InventoryService 2023 post-mortem.</span>
            </p>
          </li>
          <li className="rounded border-l-2 px-3 py-2" style={{ background: '#ECFDF5', borderColor: '#10B981' }}>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-[#065F46]">Day 11 · M. Chen (Security Eng Lead)</div>
            <p className="mt-1">
              Approved: Codex auto-patch of <code className="font-mono">dynamodb:*</code> → scoped actions, and VPC
              endpoint for Secrets Manager + RDS. Access Analyzer: 0 findings.
            </p>
          </li>
          <li className="rounded border-l-2 px-3 py-2" style={{ background: '#EFF6FF', borderColor: '#2563EB' }}>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-[#1E3A8A]">Day 17 · R. Davis (FinOps Lead)</div>
            <p className="mt-1">
              Approved provisioned concurrency on <code className="font-mono">CreateOrderFn</code> (+$180/mo) against
              $47k/hr downtime risk. Flagged for Compute Optimizer review post-hypercare.
            </p>
          </li>
          <li className="rounded border-l-2 px-3 py-2" style={{ background: '#F3F4F6', borderColor: '#6B7280' }}>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-[#111827]">Day 21 · S. Kim (SRE Lead)</div>
            <p className="mt-1">
              Go for 1% canary. Drift &lt; 0.01% over 14 days. Cutover complete at 14:02 UTC on Day 21.
            </p>
          </li>
        </ul>
      </section>

      <section className="mt-6 flex items-center gap-3 border-t pt-4" style={{ borderColor: '#E5E7EB' }}>
        <span className="text-[11px] uppercase tracking-widest text-[#6B7280]">Reviewed by</span>
        <div className="flex items-center gap-2">
          {reviewers.map((r) => (
            <span key={r.key} className="flex items-center gap-1.5 rounded-full bg-[#F3F4F6] px-2 py-1 text-[11px] font-mono">
              <span className="h-1.5 w-1.5 rounded-full" style={{ background: r.accent }} />
              {r.name}
            </span>
          ))}
        </div>
      </section>
    </article>
  );
}

function Fact({ label, value, accent }: { label: string; value: string; accent?: string }) {
  return (
    <div className="rounded-md border bg-[#F9FAFB] px-3 py-2" style={{ borderColor: '#E5E7EB' }}>
      <div className="text-[10px] uppercase tracking-widest text-[#6B7280]">{label}</div>
      <div className="mt-0.5 text-sm font-semibold" style={{ color: accent ?? '#111827' }}>{value}</div>
    </div>
  );
}
