'use client';

import { ChevronDown, ChevronRight, Search, Star } from 'lucide-react';
import { CHARACTERS } from '../data/characters';
import { MacBookFrame } from './macbook-frame';

/**
 * The Cursor-generated modernization triage report — rendered as a Notion
 * doc page (since this artifact is a long-form report, not a SaaS app
 * console). Wrapped in MacBook + Chrome chrome for visual consistency with
 * the other receipts.
 */
export function TriageReportArtifact() {
  const reviewers = [CHARACTERS.park, CHARACTERS.chen, CHARACTERS.davis, CHARACTERS.kim];

  return (
    <MacBookFrame
      url="acme.notion.site/Modernization-triage-OrdersService-9f1c2a4e"
      tabTitle="Modernization triage · OrdersService"
      browser="chrome"
    >
      <div className="bg-white text-[#37352F]">
        {/* Notion top bar */}
        <div className="flex items-center gap-3 border-b border-[#EBEBEA] bg-white px-3 py-1.5 text-[11.5px] text-[#37352F]">
          <NotionLogo />
          <span className="opacity-50">/</span>
          <span className="opacity-60">Workspaces</span>
          <ChevronRight className="h-3 w-3 opacity-40" />
          <span className="opacity-60">Acme · Engineering</span>
          <ChevronRight className="h-3 w-3 opacity-40" />
          <span className="font-semibold">Modernization triage · OrdersService</span>
          <Star className="ml-2 h-3.5 w-3.5 text-[#FFB100]" />
          <div className="ml-auto hidden items-center gap-2 md:flex">
            <span className="rounded border border-[#EBEBEA] px-2 py-0.5 text-[#787774]">Share</span>
            <Search className="h-3.5 w-3.5 text-[#787774]" />
            <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-[#FF9900] text-[10.5px] font-bold text-white">
              CA
            </span>
          </div>
        </div>

        {/* Notion page body */}
        <article className="mx-auto max-w-3xl px-8 py-6">
          {/* Cover-style title block */}
          <div className="mb-1 text-[11px] uppercase tracking-wider text-[#9B9A97]">
            Modernization triage · OrdersService
          </div>
          <h1 className="text-[28px] font-bold leading-tight text-[#37352F]">
            Target-state plan
            <span className="ml-2 align-middle text-[14px] font-mono font-semibold text-[#9B9A97]">v1.2</span>
          </h1>
          <p className="mt-2 text-[13.5px] leading-relaxed text-[#5E5C57]">
            Generated by a Cursor Cloud Agent fleet after 3 calendar days of discovery.
            Reviewed and amended over 22 days with 4 named gates.
          </p>

          {/* Metadata row (Notion property style) */}
          <dl className="mt-4 grid grid-cols-1 gap-y-1 text-[12.5px] sm:grid-cols-[140px_1fr]">
            <Prop label="Status" value={<Badge bg="#DDEDEA" fg="#0F6E5A">Approved · cutover complete</Badge>} />
            <Prop label="Owner" value="Cursor Agent (acme-ai)" />
            <Prop label="Reviewers" value={
              <span className="flex flex-wrap items-center gap-1.5">
                {reviewers.map((r) => (
                  <span key={r.key} className="inline-flex items-center gap-1 rounded bg-[#F1F1EF] px-1.5 py-0.5 text-[11px] font-mono">
                    <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: r.accent }} />
                    {r.name}
                  </span>
                ))}
              </span>
            } />
            <Prop label="Last edit" value="Day 23 · auto-merged after hyper-care close" />
            <Prop label="Linked" value={
              <span className="text-[#0B6E99]">PR #247 · Jira ORDERS-4201 · AWS orders-prod</span>
            } />
          </dl>

          <Hr />

          {/* Source state */}
          <H2>Source state</H2>
          <FactGrid
            facts={[
              { label: 'Runtime', value: 'WebSphere 8.5 + EJB' },
              { label: 'Database', value: 'Oracle 12c (EE) — EoL Dec 2027' },
              { label: 'LOC', value: '180,000' },
              { label: 'p99 latency', value: '1,240 ms', tone: 'bad' },
              { label: 'Run-rate', value: '$70,000 / mo allocated', tone: 'bad' },
              { label: 'Maintainer', value: 'None since 2019' },
            ]}
          />

          {/* Target state */}
          <H2>Target state</H2>
          <FactGrid
            facts={[
              { label: 'Runtime', value: 'AWS Lambda (Node 20)' },
              { label: 'Database', value: 'Aurora Serverless v2 (Postgres 15)' },
              { label: 'API', value: 'API Gateway · private' },
              { label: 'p99 latency', value: '340 ms', tone: 'good' },
              { label: 'Run-rate', value: '$527 / mo', tone: 'good' },
              { label: 'IAM', value: 'CIS §3.1, §4.2 compliant' },
            ]}
          />

          {/* Override log */}
          <H2>Override log</H2>
          <div className="space-y-2">
            <Override
              who="J. Park"
              role="Principal Architect"
              day="Day 3"
              tone="warn"
              body={
                <>
                  Extend dual-write from 7 to <strong>14 days</strong>. Add parity-diff Lambda (15-min cadence,
                  fail-closed @ 0.01% drift). <span className="text-[#787774]">Grounded: InventoryService 2023 post-mortem.</span>
                </>
              }
            />
            <Override
              who="M. Chen"
              role="Security Eng Lead"
              day="Day 11"
              tone="ok"
              body={
                <>
                  Approved: Codex auto-patch of <code className="rounded bg-[#F1F1EF] px-1 font-mono text-[11.5px]">dynamodb:*</code>{' '}
                  → scoped actions, plus VPC endpoint for Secrets Manager + RDS. Access Analyzer: 0 findings.
                </>
              }
            />
            <Override
              who="R. Davis"
              role="FinOps Lead"
              day="Day 17"
              tone="info"
              body={
                <>
                  Approved provisioned concurrency on <code className="rounded bg-[#F1F1EF] px-1 font-mono text-[11.5px]">CreateOrderFn</code>{' '}
                  (+$180/mo) against $47k/hr downtime risk. Flagged for Compute Optimizer review post-hypercare.
                </>
              }
            />
            <Override
              who="S. Kim"
              role="SRE Lead"
              day="Day 21"
              tone="muted"
              body={
                <>
                  Go for 1% canary. Drift &lt; 0.01% over 14 days. Cutover complete at <strong>14:02 UTC</strong>{' '}
                  on Day 21.
                </>
              }
            />
          </div>

          <Hr />

          {/* Footer reviewers chip row */}
          <div className="flex items-center gap-3 text-[11.5px] text-[#787774]">
            <span className="uppercase tracking-wider">Reviewed by</span>
            {reviewers.map((r) => (
              <span key={r.key} className="inline-flex items-center gap-1 rounded-full bg-[#F1F1EF] px-2 py-0.5 font-mono">
                <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: r.accent }} />
                {r.name}
              </span>
            ))}
          </div>
        </article>
      </div>
    </MacBookFrame>
  );
}

function NotionLogo() {
  // Minimal "N" cube glyph; reads as Notion's bug at this size.
  return (
    <span className="inline-flex h-5 w-5 items-center justify-center rounded-sm bg-[#37352F] text-[12px] font-black text-white">
      N
    </span>
  );
}

function Prop({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <>
      <dt className="flex items-center gap-1 py-0.5 text-[12px] text-[#787774]">
        <ChevronRight className="h-3 w-3" />
        {label}
      </dt>
      <dd className="py-0.5 text-[12.5px] text-[#37352F]">{value}</dd>
    </>
  );
}

function Badge({ bg, fg, children }: { bg: string; fg: string; children: React.ReactNode }) {
  return (
    <span
      className="inline-flex items-center gap-1 rounded px-1.5 py-0.5 text-[11px] font-semibold"
      style={{ background: bg, color: fg }}
    >
      <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: fg }} />
      {children}
    </span>
  );
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-5 mb-2 flex items-center gap-1 text-[18px] font-semibold text-[#37352F]">
      <ChevronDown className="h-4 w-4 opacity-50" />
      {children}
    </h2>
  );
}

function Hr() {
  return <hr className="my-5 border-[#EBEBEA]" />;
}

function FactGrid({
  facts,
}: {
  facts: { label: string; value: string; tone?: 'good' | 'bad' }[];
}) {
  return (
    <div className="grid grid-cols-1 gap-1.5 sm:grid-cols-3">
      {facts.map((f) => {
        const color = f.tone === 'good' ? '#0F6E5A' : f.tone === 'bad' ? '#B91C1C' : '#37352F';
        return (
          <div
            key={f.label}
            className="rounded-md border border-[#EBEBEA] bg-[#FBFBFA] px-3 py-2"
          >
            <div className="text-[10.5px] uppercase tracking-wider text-[#787774]">{f.label}</div>
            <div className="mt-0.5 text-[13px] font-semibold" style={{ color }}>
              {f.value}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function Override({
  who,
  role,
  day,
  body,
  tone,
}: {
  who: string;
  role: string;
  day: string;
  body: React.ReactNode;
  tone: 'warn' | 'ok' | 'info' | 'muted';
}) {
  const styles = {
    warn:   { bg: '#FEF3C7', border: '#F59E0B', label: '#78350F' },
    ok:     { bg: '#ECFDF5', border: '#10B981', label: '#065F46' },
    info:   { bg: '#EFF6FF', border: '#2563EB', label: '#1E3A8A' },
    muted:  { bg: '#F4F4F2', border: '#9B9A97', label: '#37352F' },
  }[tone];
  return (
    <div
      className="rounded-md border-l-[3px] px-3 py-2 text-[12.5px] leading-snug"
      style={{ background: styles.bg, borderColor: styles.border, color: '#37352F' }}
    >
      <div className="mb-0.5 text-[11px] font-semibold uppercase tracking-wider" style={{ color: styles.label }}>
        {day} · {who} · {role}
      </div>
      <div>{body}</div>
    </div>
  );
}
